backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - label: PDF
    name: pdf
    folder: pdf
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - label: file
        name: file
        widget: file
        media_library:
          config:
            multiple: true
      - label: thumbnail
        name: thumbnail
        widget: file
        media_library:
          config:
            multiple: true
  - name: generalConfig
    label: "Site Configuration"
    files:
      - file: 'src/site-description.md'
        label: siteDescription
        name: siteDescription
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "navbar" }
          - { label: "Site description", name: "sideDescription", widget: "string", hint: "This will go into the google" }
      - file: 'src/pdfs-per-section.md'
        label: pdfsPerSection
        name: pdfsPerSection
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "navbar" }
          - label: "PDFs per section"
            name: "pdfsPerSection"
            widget: "number"
            default: 4
            valueType: "int"
            min: 1
            max: 6
            step: 1
      - file: 'src/about-me-items.md'
        label: aboutMeItems
        name: aboutMeItems
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "navbar" }
          - label: "About me items"
            name: "aboutMeItems"
            widget: "list"
            fields:
            - { label: "content", name: "content", widget: "markdown" }



